name: Tests
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iden3/circom:0.0.1
      options: --user 1001 # https://github.com/cypress-io/github-action/issues/446#issuecomment-987015822
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Install node_modules
      run: npm install
    - name: Test circom circuits
      run: npm run test
